plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss

overrides:
  - files: "*.astro"
    options:
      parser: astro

arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
jsxSingleQuote: false
printWidth: 120
proseWrap: always
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "none"
useTabs: false
experimentalTernaries: true
